-- Las Casita Project Manager — Supabase schema
-- Run this once in Supabase: Dashboard -> SQL Editor -> New query -> paste -> Run

-- Step 1: remove the old (unused) schema from a previous tool, confirmed empty of
-- anything worth keeping. Safe to skip if these tables don't exist.
drop table if exists quote_items cascade;
drop table if exists payment_schedules cascade;
drop table if exists quotes cascade;
drop table if exists material_expenses cascade;
drop table if exists project_stages cascade;
drop table if exists quote_categories cascade;
drop table if exists attendance_entries cascade;
drop table if exists project_managers cascade;
drop table if exists workers cascade;
drop table if exists projects cascade;
drop table if exists profiles cascade;

drop type if exists public.quote_calc_mode cascade;
drop type if exists public.quote_status cascade;
drop type if exists public.inspection_status cascade;
drop type if exists public.app_role cascade;
drop type if exists public.project_status cascade;

-- Step 2: create this app's tables

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  ssn text default '',
  id_number text default '',
  default_daily_rate numeric not null default 0,
  active boolean not null default true,
  notes text default '',
  created_at timestamptz not null default now()
);

create table if not exists projects (
  id bigint generated by default as identity primary key,
  name text not null,
  address text default '',
  client_name text default '',
  status text not null default 'active', -- active | on_hold | completed
  start_date date,
  est_end_date date,
  quoted_total numeric not null default 0,
  notes text default '',
  created_at timestamptz not null default now()
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  project_id bigint not null references projects(id) on delete cascade,
  work_date date not null,
  days numeric not null default 1,
  rate numeric not null default 0,
  payment_status text not null default 'unpaid', -- unpaid | paid
  notes text default ''
);

create table if not exists materials (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  purchase_date date not null,
  vendor text default '',
  description text default '',
  category text default '',
  mode text not null default 'flat', -- flat | qty
  qty numeric,
  unit_price numeric,
  amount numeric not null default 0,
  payment_status text not null default 'unpaid', -- unpaid | paid
  payment_method text default '',
  invoice_number text default ''
);

create table if not exists stages (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  name text not null,
  department text default '',
  status text not null default 'scheduled', -- scheduled | passed | failed
  inspection_date date,
  completed_date date,
  notes text default '',
  sort_order integer not null default 0
);

create table if not exists quotes (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete set null,
  quote_no text default '',
  quote_date date,
  client_name text default '',
  address text default '',
  scope text default '',
  referral_source text default '',
  estimate_period text default '',
  start_date date,
  est_end_date date,
  items jsonb not null default '[]',
  payment_schedule jsonb not null default '[]',
  exclusions jsonb not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists settings (
  id smallint primary key default 1 check (id = 1),
  company_name text default 'Las Casita Inc.',
  company_addr1 text default '',
  company_addr2 text default '',
  company_email text default '',
  contact1 text default '',
  contact2 text default '',
  password_salt text,
  password_hash text
);

create index if not exists idx_attendance_project on attendance(project_id);
create index if not exists idx_attendance_employee on attendance(employee_id);
create index if not exists idx_attendance_date on attendance(work_date);
create index if not exists idx_materials_project on materials(project_id);
create index if not exists idx_stages_project on stages(project_id);
create index if not exists idx_quotes_project on quotes(project_id);

-- This app connects using the Supabase "secret" key from a trusted server only
-- (never from the browser), so Row Level Security is left off — the server itself
-- enforces the password/session gate before any of these tables are touched.

-- Change orders (added later)
create table if not exists change_orders (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id) on delete cascade,
  order_no text default '',
  order_date date,
  title text default '',
  items jsonb not null default '[]',
  status text not null default 'pending', -- pending | approved | rejected
  approved_date date,
  client_name text default '',
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_change_orders_project on change_orders(project_id);
alter table change_orders disable row level security;
